-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 15:34:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema arbolitoDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema arbolitoDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `arbolitoDB` DEFAULT CHARACTER SET utf8 ;
USE `arbolitoDB` ;

-- -----------------------------------------------------
-- Table `arbolitoDB`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `arbolitoDB`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `arbolitoDB`.`Usuario` (
  `dni` INT NOT NULL,
  `nick` VARCHAR(45) NULL,
  `passwrd` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`),
  UNIQUE INDEX `nick_UNIQUE` (`nick` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arbolitoDB`.`divisas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `arbolitoDB`.`divisas` ;

CREATE TABLE IF NOT EXISTS `arbolitoDB`.`divisas` (
  `simbolo` VARCHAR(10) NOT NULL,
  `cantidad` FLOAT NULL,
  `nombre` VARCHAR(45) NULL,
  `Usuario_dni` INT NOT NULL,
  PRIMARY KEY (`Usuario_dni`, `simbolo`),
  INDEX `fk_divisas_Usuario_idx` (`Usuario_dni` ASC) VISIBLE,
  CONSTRAINT `fk_divisas_Usuario`
    FOREIGN KEY (`Usuario_dni`)
    REFERENCES `arbolitoDB`.`Usuario` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
